apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content
data:
  index.html: |
     <html>
        <head>
           <title> Teste site </title>
        </head>
        <body>
          <h1> Testando o ConfigMap </h1:
        </body>
     </html>