apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        volumeMounts:
          - name: nginx-content-folder
            mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
        - name: nginx-content-folder
          configMap:
            name: nginx-content