apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-deployment-service
  namespace: default
spec:
  ports:
  - nodePort: 30773
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
